LATEX = pdflatex
XSLTP = xsltproc

all: xhtml charactersheet

xhtml: Apathy.xml Apathy.html.xsl Apathy.css
	xsltproc --stringparam TOC yes --stringparam Title "Apathy Game Rules" -o Apathy.xhtml Tools/Display.xsl Doc/Apathy.xhtml

charactersheet: CharacterSheet.tex
	pdflatex CharacterSheet.tex >& CharacterSheet.pdflatex
